ez-ql/ez-ql-electron-react

package-lock.json
package.json
public/main.js

follow node-postgres docs to configure client (and pool for later)
connection is currently to plantr db b/c I'm not seeded - this needs to change

feat(config): set up postgres connection in /public/main.js

---

package-lock.json
package.json
src/App.js
src/MakeQuery.js

Created component on frontend that shows a sample table and fields. Selecting a table and fields produces a console log of the squel query based on the selections.

Fix (frontend): Front end now renders POC query

---

package-lock.json
public/index.html
public/main.js
src/MakeQuery.js

Adding the initial ipc methods

feat(MakeQuery): connect to back end

---

public/main.js
src/MakeQuery.js

Created the global sharedObj and the initial schema load query. Initial schema data is now available upon starting the application.

feat(config) - serve up initial schema data

---

src/MakeQuery.js
src/StartQuery.js
src/Table.js

- removed 'from' reference from makeQuery so it could no longer overwrite the original selection
- added 'qualified fields' to qualified fields array on global object, whenever preview button is clicked.

Feat: updated how and when data is saved to global object on -setting from table - previewing data

---

src/Aggregate.js
src/App.js
src/Filter.js
src/MakeQuery.js
src/Sort.js
src/Stepper.js

Added Stepper component for aggregating, filtering, and sorting
Fixed bugs in agg and filter so squel query now works

Feat: Stepper for refining query

---

public/main.js

Initial data load now includes information related to the user and available databases, projects, and queries

feat(backend): load user and project data

---

src/FieldButtons.js

connects to #60 
changes: 
* increased font size on tool tip text
* added line break on tool tip text
* removed non-used styling

fix(frontend): adjust formatting of tooltip text -#60

---

src/JoinModal.js
src/Joins.js
src/MakeQuery.js

Added Join Modal component and adjusted global object so that fields are added to the object when selected

Feat: added Join Modal

---

package-lock.json
src/FinalizeQuery.js
src/PreviewModal.js
src/PreviewTabs.js
src/Stepper.js
src/Table.js

* data in PreviewTabs was incorrectly labelled 'previewData' --> changed to data everywhere

fix: bug with data not carrying over into preview component - fixed

---

public/index.html
src/Aggregate.js
src/App.css
src/Filter.js
src/FinalizeQuery.js
src/Joins.js
src/MakeQuery.js
src/SelectFields.js
src/SelectTable.js
src/Selector/Selector.js
src/Sort.js
src/Stepper.js
src/Table.js

fix(aggregate/filter/sort, carousel, preview table) styling adjustments
connect to #87

Filter styling

---

src/Joins.js
src/ScrollMenu.js

Fix: default join selection defaults to inner join

---

src/Aggregate.js
src/Filter.js
src/Sort.js
src/Toasts.js

Submit buttons only active when fields have been entered/selected for Agg, Filter, Sort
No longer able to enter non-numerical inputs when field type should only accept numbers in Filter component

#139, #119 - Field validation

---

src/Aggregate.js

this is tested and works again

fixed props for submit button to repair agg functionality

---

package-lock.json
src/Aggregate.js
src/Filter.js
src/MakeQuery.js
src/OptionalModal.js
src/PreviewTabs.js
src/Sort.js

Added optional step modal (needs styling) #133 
Added current selection to second preview tab #120 
Removed current selection from sort by page #115 
Aggregator only shows available aggregators based on selection #129  
Able to select multiple aggregators for one field #111 
Removed before and after options for decimals and integers on filter page #140 
Removed select another aggregator button #132

Fixed bugs added optional modal

---

src/Aggregate.js
src/Sort.js

toast is back! needed to move the wrapped component out one div level (shrug)

restored toast and tested agg selection functionality

---

src/App.css
src/App.js
src/FinalizeQuery.js
src/Project.js
src/SelectFields.js
src/SelectTable.js
src/Selector/Selector.js
src/StartQuery.js
src/Stepper.js

feat(stepper and single project): styling applied
connects to #138,

feat(stepper, single project): styling is complete

---

src/Aggregate.js
src/Filter.js
src/ScrollMenu.js

submit button returns to disabled status when appropriate

submit button is inactive until field to agg is selected

---

public/main.js
src/FinalizeQuery.js
src/PreviewModal.js
src/PreviewPanel.js
src/PreviewTabs.js
src/Project.js
src/StartOverButton.js
src/Stepper.js

feat(finalize): finalize in stepper and styled. Finalize also works from single project view.
#158 #118 #155

Finalize styling

---

src/Aggregate.js
src/OptionalModal.js
src/Stepper.js

Styled optional steps modal
Fixed aggregate bugs

Style optional modal

---

src/Aggregate.js
src/Filter.js
src/MakeQuery.js
src/SelectFields.js
src/SelectTable.js
src/StartQuery.js

changed titles for Select a Table, Select Fields, and Select Agg

#136 - changed titles to calls to action

---

package-lock.json
package.json
src/App.css
src/InfoModal.js
src/JoinModal.js
src/Joins.js
src/OptionalModal.js
src/StartModal.js
src/StartQuery.js
src/Stepper.js

Added start modal #167
Added info button and modal #166
Styling on all modals for consistency

Add start modal #167 and info button #166

---

README.md

removed link to splash page b/c we won't be uploading binary files for download right now

remove link to splash page
